"""CuratorWorkflow — Temporal orchestrator for the Curator agent.

One workflow run executes a full knowledge-base quality scan for a single
project: orphan detection, duplicate detection, and contradiction detection.
The workflow is a thin wrapper that acquires the per-project semaphore, runs
the ``run_curator`` activity, and releases the semaphore in a ``finally``
block.

Workflow id convention: ``curator-{uuid}`` generated by the API caller.
"""
from __future__ import annotations

from datetime import timedelta
from typing import Any

from temporalio import workflow
from temporalio.common import RetryPolicy

with workflow.unsafe.imports_passed_through():
    from worker.activities.semaphore_activity import (
        acquire_project_semaphore,
        release_project_semaphore,
    )


_SEM_PURPOSE = "curator"
_SEM_ACQUIRE_TIMEOUT = timedelta(minutes=15)
_ACTIVITY_TIMEOUT = timedelta(minutes=30)


@workflow.defn(name="CuratorWorkflow")
class CuratorWorkflow:
    @workflow.run
    async def run(self, inp: dict[str, Any]) -> dict[str, Any]:
        project_id = inp["project_id"]
        workspace_id = inp["workspace_id"]
        holder_id = workflow.info().workflow_id

        workflow.logger.info(
            "CuratorWorkflow start: project=%s workspace=%s",
            project_id,
            workspace_id,
        )

        await workflow.execute_activity(
            acquire_project_semaphore,
            {
                "workspace_id": workspace_id,
                "project_id": project_id,
                "holder_id": holder_id,
                "purpose": _SEM_PURPOSE,
            },
            start_to_close_timeout=_SEM_ACQUIRE_TIMEOUT,
            heartbeat_timeout=timedelta(seconds=30),
            retry_policy=RetryPolicy(maximum_attempts=2),
        )
        try:
            result = await workflow.execute_activity(
                "run_curator",
                inp,
                start_to_close_timeout=_ACTIVITY_TIMEOUT,
                heartbeat_timeout=timedelta(minutes=5),
                retry_policy=RetryPolicy(
                    initial_interval=timedelta(seconds=2),
                    maximum_interval=timedelta(seconds=60),
                    backoff_coefficient=2.0,
                    maximum_attempts=2,
                ),
            )
        finally:
            try:
                await workflow.execute_activity(
                    release_project_semaphore,
                    {
                        "workspace_id": workspace_id,
                        "project_id": project_id,
                        "holder_id": holder_id,
                    },
                    start_to_close_timeout=timedelta(seconds=60),
                    retry_policy=RetryPolicy(maximum_attempts=1),
                )
            except Exception as exc:  # noqa: BLE001
                workflow.logger.warning(
                    "CuratorWorkflow: semaphore release failed (slot will "
                    "auto-expire): %s",
                    exc,
                )

        workflow.logger.info(
            "CuratorWorkflow done: orphans=%d duplicates=%d contradictions=%d suggestions=%d",
            result.get("orphans_found", 0),
            result.get("duplicates_found", 0),
            result.get("contradictions_found", 0),
            result.get("suggestions_created", 0),
        )
        return result
