"""NarratorWorkflow — Temporal orchestrator for the Narrator agent.

One workflow run produces one podcast audio file (or a script-only result
when TTS is unavailable) from a single wiki note. The workflow is a thin
wrapper: it runs the ``run_narrator`` activity with a generous timeout that
accounts for both LLM script generation and TTS synthesis (which can be slow
on long notes).

Workflow id convention: ``narrator-{uuid}`` generated by the API caller.
"""
from __future__ import annotations

from datetime import timedelta
from typing import Any

from temporalio import workflow
from temporalio.common import RetryPolicy

with workflow.unsafe.imports_passed_through():
    import os as _os

# Read the env override once at module import (outside the workflow class)
# so Temporal's deterministic sandbox sees a fixed value per worker boot.
_MAX_DURATION_SEC = int(_os.environ.get("NARRATOR_MAX_DURATION_SEC", "900"))
_ACTIVITY_TIMEOUT = timedelta(seconds=_MAX_DURATION_SEC + 300)


@workflow.defn(name="NarratorWorkflow")
class NarratorWorkflow:
    @workflow.run
    async def run(self, inp: dict[str, Any]) -> dict[str, Any]:
        workflow.logger.info(
            "NarratorWorkflow start: note_id=%s workspace=%s",
            inp.get("note_id"),
            inp.get("workspace_id"),
        )

        result = await workflow.execute_activity(
            "run_narrator",
            inp,
            start_to_close_timeout=_ACTIVITY_TIMEOUT,
            heartbeat_timeout=timedelta(minutes=5),
            retry_policy=RetryPolicy(maximum_attempts=2),
        )

        workflow.logger.info(
            "NarratorWorkflow done: has_audio=%s script_turns=%d",
            result.get("has_audio", False),
            len(result.get("script", [])),
        )
        return result
