"""ResearchWorkflow — Temporal orchestrator for the Research agent.

One workflow run answers one query. The workflow is a thin wrapper: it
acquires the per-project semaphore, runs the ``run_research`` activity, and
releases the semaphore in a ``finally``. Sub-query retrieval and LLM calls
all live inside the activity (non-deterministic).

Workflow id convention: ``research-{uuid}`` generated by the caller. We do
NOT derive it from the query text — duplicate questions should each get
their own run so the trajectory table reflects user intent truthfully.
"""
from __future__ import annotations

from datetime import timedelta
from typing import Any

from temporalio import workflow
from temporalio.common import RetryPolicy

with workflow.unsafe.imports_passed_through():
    from worker.activities.semaphore_activity import (
        acquire_project_semaphore,
        release_project_semaphore,
    )


_SEM_PURPOSE = "research"
_SEM_ACQUIRE_TIMEOUT = timedelta(minutes=15)
_ACTIVITY_TIMEOUT = timedelta(minutes=10)


@workflow.defn(name="ResearchWorkflow")
class ResearchWorkflow:
    @workflow.run
    async def run(self, inp: dict[str, Any]) -> dict[str, Any]:
        project_id = inp["project_id"]
        holder_id = workflow.info().workflow_id

        workflow.logger.info(
            "ResearchWorkflow start: query=%r project=%s",
            inp.get("query"),
            project_id,
        )

        await workflow.execute_activity(
            acquire_project_semaphore,
            {
                "project_id": project_id,
                "holder_id": holder_id,
                "purpose": _SEM_PURPOSE,
            },
            start_to_close_timeout=_SEM_ACQUIRE_TIMEOUT,
            heartbeat_timeout=timedelta(seconds=30),
            retry_policy=RetryPolicy(maximum_attempts=2),
        )
        try:
            result = await workflow.execute_activity(
                "run_research",
                inp,
                start_to_close_timeout=_ACTIVITY_TIMEOUT,
                heartbeat_timeout=timedelta(minutes=2),
                retry_policy=RetryPolicy(
                    initial_interval=timedelta(seconds=2),
                    maximum_interval=timedelta(seconds=60),
                    backoff_coefficient=2.0,
                    maximum_attempts=3,
                ),
            )
        finally:
            # Best-effort release — a failed release leaves a slot that
            # expires on its TTL, so the project never deadlocks even if
            # this activity itself fails.
            try:
                await workflow.execute_activity(
                    release_project_semaphore,
                    {"project_id": project_id, "holder_id": holder_id},
                    start_to_close_timeout=timedelta(seconds=60),
                    retry_policy=RetryPolicy(maximum_attempts=1),
                )
            except Exception as exc:  # noqa: BLE001
                workflow.logger.warning(
                    "ResearchWorkflow: semaphore release failed (slot will "
                    "auto-expire): %s",
                    exc,
                )

        workflow.logger.info(
            "ResearchWorkflow done: citations=%d", len(result.get("citations", []))
        )
        return result
