"""StalenessWorkflow — Temporal orchestrator for the Staleness agent.

One workflow run scans one project for stale wiki notes. The workflow is a
thin wrapper: it executes the ``run_staleness`` activity with a 30-minute
timeout and at most 2 attempts.

Workflow id convention: ``staleness-{uuid}`` generated by the caller.
"""
from __future__ import annotations

from datetime import timedelta
from typing import Any

from temporalio import workflow
from temporalio.common import RetryPolicy


@workflow.defn(name="StalenessWorkflow")
class StalenessWorkflow:
    @workflow.run
    async def run(self, inp: dict[str, Any]) -> dict[str, Any]:
        workflow.logger.info(
            "StalenessWorkflow start: project=%s stale_days=%s",
            inp.get("project_id"),
            inp.get("stale_days", 90),
        )

        result = await workflow.execute_activity(
            "run_staleness",
            inp,
            start_to_close_timeout=timedelta(minutes=30),
            heartbeat_timeout=timedelta(minutes=5),
            retry_policy=RetryPolicy(maximum_attempts=2),
        )

        workflow.logger.info(
            "StalenessWorkflow done: alerts_created=%d",
            result.get("alerts_created", 0),
        )
        return result
