"""StalenessWorkflow — Temporal orchestrator for the Staleness agent.

One workflow run scans one project for stale wiki notes. The workflow is a
thin wrapper: it acquires the per-project semaphore, executes the
``run_staleness`` activity with a 30-minute timeout, then releases the slot.

Workflow id convention: ``staleness-{uuid}`` generated by the caller.
"""
from __future__ import annotations

from datetime import timedelta
from typing import Any

from temporalio import workflow
from temporalio.common import RetryPolicy

with workflow.unsafe.imports_passed_through():
    from worker.activities.semaphore_activity import (
        acquire_project_semaphore,
        release_project_semaphore,
    )

_SEM_PURPOSE = "staleness"
_SEM_ACQUIRE_TIMEOUT = timedelta(minutes=30)


@workflow.defn(name="StalenessWorkflow")
class StalenessWorkflow:
    @workflow.run
    async def run(self, inp: dict[str, Any]) -> dict[str, Any]:
        project_id = inp["project_id"]
        workspace_id = inp["workspace_id"]
        holder_id = workflow.info().workflow_id

        workflow.logger.info(
            "StalenessWorkflow start: project=%s stale_days=%s",
            project_id,
            inp.get("stale_days", 90),
        )

        await workflow.execute_activity(
            acquire_project_semaphore,
            {
                "workspace_id": workspace_id,
                "project_id": project_id,
                "holder_id": holder_id,
                "purpose": _SEM_PURPOSE,
            },
            start_to_close_timeout=_SEM_ACQUIRE_TIMEOUT,
            heartbeat_timeout=timedelta(seconds=30),
            retry_policy=RetryPolicy(maximum_attempts=2),
        )
        try:
            result = await workflow.execute_activity(
                "run_staleness",
                inp,
                start_to_close_timeout=timedelta(minutes=30),
                heartbeat_timeout=timedelta(minutes=5),
                retry_policy=RetryPolicy(maximum_attempts=2),
            )
        finally:
            try:
                await workflow.execute_activity(
                    release_project_semaphore,
                    {
                        "workspace_id": workspace_id,
                        "project_id": project_id,
                        "holder_id": holder_id,
                    },
                    start_to_close_timeout=timedelta(seconds=60),
                    retry_policy=RetryPolicy(maximum_attempts=1),
                )
            except Exception as exc:  # noqa: BLE001 — slot auto-expires on TTL
                workflow.logger.warning(
                    "StalenessWorkflow: semaphore release failed (slot will "
                    "auto-expire): %s",
                    exc,
                )

        workflow.logger.info(
            "StalenessWorkflow done: alerts_created=%d",
            result.get("alerts_created", 0),
        )
        return result
