"""SynthesisWorkflow — Temporal orchestrator for the Synthesis agent.

One workflow run produces one synthesized essay note from a set of source
note IDs. The workflow is a thin wrapper: it acquires the per-project
semaphore, runs the ``run_synthesis`` activity, and releases the semaphore
in a ``finally`` block.

Workflow id convention: ``synthesis-{uuid}`` generated by the API caller.
"""
from __future__ import annotations

from datetime import timedelta
from typing import Any

from temporalio import workflow
from temporalio.common import RetryPolicy

with workflow.unsafe.imports_passed_through():
    from worker.activities.semaphore_activity import (
        acquire_project_semaphore,
        release_project_semaphore,
    )


_SEM_PURPOSE = "synthesis"
_SEM_ACQUIRE_TIMEOUT = timedelta(minutes=15)
_ACTIVITY_TIMEOUT = timedelta(minutes=10)


@workflow.defn(name="SynthesisWorkflow")
class SynthesisWorkflow:
    @workflow.run
    async def run(self, inp: dict[str, Any]) -> dict[str, Any]:
        project_id = inp["project_id"]
        workspace_id = inp["workspace_id"]
        holder_id = workflow.info().workflow_id

        workflow.logger.info(
            "SynthesisWorkflow start: note_ids=%r project=%s",
            inp.get("note_ids"),
            project_id,
        )

        await workflow.execute_activity(
            acquire_project_semaphore,
            {
                "workspace_id": workspace_id,
                "project_id": project_id,
                "holder_id": holder_id,
                "purpose": _SEM_PURPOSE,
            },
            start_to_close_timeout=_SEM_ACQUIRE_TIMEOUT,
            heartbeat_timeout=timedelta(seconds=30),
            retry_policy=RetryPolicy(maximum_attempts=2),
        )
        try:
            result = await workflow.execute_activity(
                "run_synthesis",
                inp,
                start_to_close_timeout=_ACTIVITY_TIMEOUT,
                heartbeat_timeout=timedelta(minutes=2),
                retry_policy=RetryPolicy(
                    initial_interval=timedelta(seconds=2),
                    maximum_interval=timedelta(seconds=60),
                    backoff_coefficient=2.0,
                    maximum_attempts=2,
                ),
            )
        finally:
            try:
                await workflow.execute_activity(
                    release_project_semaphore,
                    {
                        "workspace_id": workspace_id,
                        "project_id": project_id,
                        "holder_id": holder_id,
                    },
                    start_to_close_timeout=timedelta(seconds=60),
                    retry_policy=RetryPolicy(maximum_attempts=1),
                )
            except Exception as exc:  # noqa: BLE001
                workflow.logger.warning(
                    "SynthesisWorkflow: semaphore release failed (slot will "
                    "auto-expire): %s",
                    exc,
                )

        workflow.logger.info(
            "SynthesisWorkflow done: note_id=%s word_count=%d",
            result.get("note_id", ""),
            result.get("word_count", 0),
        )
        return result
