"""OpenCairn agent runtime — thin facade over LangGraph + langchain-core."""
from runtime.agent import Agent
from runtime.eval import (
    AgentEvaluator,
    DEFAULT_CRITERIA,
    EvalCase,
    EvalResult,
    ExpectedHandoff,
    ExpectedToolCall,
    ScoreResult,
    load_case_file,
    load_cases,
    score_trajectory,
)
from runtime.events import (
    AgentEnd,
    AgentError,
    AgentEvent,
    AgentStart,
    AwaitingInput,
    CustomEvent,
    Handoff,
    ModelEnd,
    Scope,
    ToolResult,
    ToolUse,
)
from runtime.langgraph_bridge import stream_graph_as_events
from runtime.hooks import (
    AgentHook,
    HookChain,
    HookRegistry,
    ModelHook,
    ModelRequest,
    ModelResponse,
    ToolHook,
)
from runtime.tool_declarations import (
    build_gemini_declarations,
    build_ollama_declarations,
)
from runtime.tools import (
    Tool,
    ToolContext,
    get_tool,
    get_tools_for_agent,
    hash_input,
    tool,
)
from runtime.trajectory import (
    LocalFSTrajectoryStorage,
    TrajectoryStorage,
    TrajectoryWriter,
    resolve_storage_from_env,
)

__all__ = [
    "Agent",
    "AgentEnd",
    "AgentError",
    "AgentEvaluator",
    "AgentEvent",
    "AgentHook",
    "AgentStart",
    "AwaitingInput",
    "CustomEvent",
    "DEFAULT_CRITERIA",
    "EvalCase",
    "EvalResult",
    "ExpectedHandoff",
    "ExpectedToolCall",
    "Handoff",
    "HookChain",
    "HookRegistry",
    "LocalFSTrajectoryStorage",
    "ModelEnd",
    "ModelHook",
    "ModelRequest",
    "ModelResponse",
    "Scope",
    "ScoreResult",
    "Tool",
    "ToolContext",
    "ToolHook",
    "ToolResult",
    "ToolUse",
    "TrajectoryStorage",
    "TrajectoryWriter",
    "build_gemini_declarations",
    "build_ollama_declarations",
    "get_tool",
    "get_tools_for_agent",
    "hash_input",
    "load_case_file",
    "load_cases",
    "resolve_storage_from_env",
    "score_trajectory",
    "stream_graph_as_events",
    "tool",
]
